import type { IndicatorSignal } from "@/types/indicator-signals"
import type { BacktestConfig, BacktestJob, SignalObservation } from "@/types/backtest"
import type {
  PortfolioEquityPage,
  PortfolioRunMetadata,
  PortfolioSimulationPublicResult,
  PortfolioTradePage,
} from "@/types/portfolio"

export const backtestSignal: IndicatorSignal = {
  status: "available",
  direction: "bullish",
  signal: "bullish_cross",
  state: "above_signal",
  strength: 0.75,
  reason: "Signal technique calculé à cet instant.",
  raw_value: 31.4,
}

export const portfolioPublicResult: PortfolioSimulationPublicResult = {
  version: 1,
  quote_asset: "USDC",
  summary: {
    version: 1,
    quote_asset: "USDC",
    initial_capital: "10000",
    final_cash: "10350.25",
    final_equity: "10350.25",
    net_profit: "350.25",
    total_return_ratio: "0.035025",
    realized_pnl: "350.25",
    unrealized_pnl: "0",
    total_fees: "20.1",
    trade_count: 1,
    winning_trade_count: 1,
    losing_trade_count: 0,
    breakeven_trade_count: 0,
    win_rate: "1",
    average_trade_return: "0.035025",
    max_drawdown_ratio: "0.012",
    exposure_ratio: "0.75",
    open_position_count: 0,
  },
  has_trades: true,
  has_equity_curve: true,
}

export const portfolioMetadata: PortfolioRunMetadata = {
  version: 1,
  schema_version: 1,
  engine_version: "portfolio-engine-v1",
  quote_asset: "USDC",
  summary: portfolioPublicResult.summary,
  details_status: "complete",
  order_count: 2,
  execution_count: 2,
  trade_count: 1,
  equity_point_count: 2,
  available_after_restart: true,
}

export const portfolioTradePage: PortfolioTradePage = {
  items: [{
    version: 1,
    sequence: 0,
    trade_id: "trade-000001",
    position_id: "position-000001",
    symbol: "BTC/USDC",
    quote_asset: "USDC",
    entry_observation_id: "observation-1",
    exit_observation_id: null,
    entry_time: "2026-07-01T04:00:00Z",
    exit_time: "2026-07-02T00:00:00Z",
    entry_price: "100",
    exit_price: "110",
    quantity: "10",
    entry_fee: "1",
    exit_fee: "1.1",
    gross_exit_proceeds: "1100",
    net_exit_proceeds: "1098.9",
    realized_pnl: "98.9",
    return_ratio: "0.0989",
    duration_bars: 5,
    exit_reason: "end_of_test",
  }],
  total: 1,
  offset: 0,
  limit: 50,
  has_more: false,
}

export const portfolioEquityPage: PortfolioEquityPage = {
  items: [
    {
      version: 1,
      sequence: 0,
      timestamp: "2026-07-01T00:00:00Z",
      cash: "10000",
      position_value: "0",
      equity: "10000",
      realized_pnl_cumulative: "0",
      unrealized_pnl: "0",
      fees_cumulative: "0",
      drawdown_ratio: "0",
    },
    {
      version: 1,
      sequence: 1,
      timestamp: "2026-07-02T00:00:00Z",
      cash: "10350.25",
      position_value: "0",
      equity: "10350.25",
      realized_pnl_cumulative: "350.25",
      unrealized_pnl: "0",
      fees_cumulative: "20.1",
      drawdown_ratio: "0.012",
    },
  ],
  total: 2,
  offset: 0,
  limit: 1000,
  has_more: false,
  sampled: true,
  source_point_count: 2,
}

export function createObservation(
  overrides: Partial<SignalObservation> = {},
): SignalObservation {
  return {
    id: 1,
    job_id: "job-1",
    symbol: "BTC/USDC",
    timeframe: "4h",
    decision_time: "2026-07-29T12:00:00Z",
    snapshot_status: "confirmed",
    accepted: true,
    rejection_stage: null,
    rejection_reason: null,
    close: 102.5,
    rsi: 31.4,
    trend_score: 2,
    trend_states: { "4h": "bullish" },
    macd_signal: "bullish",
    bollinger_position: "near_oversold",
    stochastic_signal: "bullish_cross",
    confluence_score: 74,
    confluence_grade: "B",
    confluence_factors: { rsi: 0.75 },
    confluence_breakdown: { rsi: 15 },
    availability: { rsi: "available" },
    indicator_signals: { rsi: backtestSignal },
    filter_trace: [],
    algorithm_version: "signal-evaluation-v2",
    profile_id: "inline",
    profile_fingerprint: "sha256:test",
    dataset_version: "dataset-test",
    calculation_mode: "canonical",
    schema_version: 2,
    source_ohlcv: { open: 100, high: 103, low: 99, close: 102.5, volume: 10 },
    raw_values: { rsi: 31.4 },
    classes: { macd: "bullish" },
    configured_weights: { rsi: 0.2 },
    effective_weights: { rsi: 20 },
    divergences: [],
    quality: { available_bars: 60 },
    ...overrides,
  }
}

export function createBacktestJob(
  overrides: Partial<BacktestJob> = {},
): BacktestJob {
  return {
    id: "job-1",
    status: "completed",
    config: {
      symbols: ["BTC/USDC"],
      start: "2026-07-01T00:00:00Z",
      end: "2026-07-29T00:00:00Z",
      signal_config: {} as BacktestConfig["signal_config"],
      horizons: [1, 3, 6],
      replay_mode: "every_bar",
      entry_policy: "signal_close",
      gap_policy: "reject_range",
      fee_bps: 10,
      slippage_bps: 5,
      snapshot_status: "confirmed",
    },
    progress: {
      processed: 100,
      total: 100,
      observations: 1,
      current_symbol: null,
      phase: "completed",
      percent: 100,
    },
    summary: null,
    correlations: null,
    ablations: null,
    warnings: [],
    error: null,
    created_at: "2026-07-29T00:00:00Z",
    started_at: "2026-07-29T00:00:01Z",
    completed_at: "2026-07-29T00:01:00Z",
    dataset_version: "dataset-test",
    algorithm_version: "signal-evaluation-v2",
    checkpoint: null,
    ...overrides,
  }
}
