import type { ScanConfig } from "@/types/scanner"

export function createScanConfig(overrides: Partial<ScanConfig> = {}): ScanConfig {
  return {
    exchange_id: "binance",
    market_type: "spot",
    quote: "USDC",
    exclude_stable_pairs: true,
    max_pairs: null,
    timeframe: "4h",
    min_ohlcv_bars: 200,
    max_concurrency: 6,
    max_retries: 3,
    retry_delay_seconds: 1.5,
    use_rsi: true,
    rsi_period: 14,
    rsi_threshold: 35,
    use_ma: true,
    use_sma: true,
    use_ema: true,
    sma_periods: [20, 50],
    ema_periods: [20, 50],
    ma_timeframes: ["1w", "1d", "4h"],
    min_trend_score: 2,
    use_macd: true,
    macd_fast_period: 12,
    macd_slow_period: 26,
    macd_signal_period: 9,
    use_bollinger: true,
    bollinger_period: 20,
    bollinger_std_dev: 2,
    use_stochastic: true,
    stochastic_k_period: 14,
    stochastic_d_period: 3,
    stochastic_oversold: 20,
    stochastic_overbought: 80,
    use_confluence_score: true,
    min_confluence_score: 60,
    confluence_weights: {
      rsi: 20,
      trend: 25,
      macd: 20,
      bollinger: 20,
      stochastic: 15,
    },
    filter_macd_signal: null,
    filter_bb_position: null,
    filter_stoch_signal: null,
    ...overrides,
  }
}
